# Generated by Django 4.2.1 on 2023-07-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_gallery_url_gallery_upload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact_us',
            table='contact_us',
        ),
    ]
