# Generated by Django 4.2.1 on 2023-07-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_contact_us_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact_us',
            table='Contact_us',
        ),
    ]
